package com.example.swadebuilder.model

val SAVAGE_PATHFINDER_ALLOWLIST = setOf(
    // 1. Materiais Especiais
    "Adamante",
    "Madeira Negra",
    "Couro de Dragão",
    "Ferro Frio",
    "Mithral",
    "Prata Alquímica",

    // 2. Equipamento de Aventura e Ferramentas - Geral
    "Agulha", "Agulha de Costura",
    "Algemas",
    "Ampulheta",
    "Anzol",
    "Apito de cerâmica", "Apito",
    "Arpéu",
    "Bolsa de cinto", "Bolsa",
    "Caneca", "Caneca de cerâmica", "Copo de cerâmica",
    "Caneta Tinteiro",
    "Cera de Vedação", "Cera para lacre",
    "Cesto", "Cesta",
    "Cobertor",
    "Corda de cânhamo", "Corda",
    "Corda de seda",
    "Corrente",
    "Espelho pequeno de aço", "Espelho pequeno",
    "Espigão", "Pitão",
    "Estojo de mapa", "Estojo de pergaminho",
    "Estrepes",
    "Frasco de cerâmica", "Jarro de cerâmica",
    "Frasco pequeno", "Frasco",
    "Garrafa de vidro", "Garrafa",
    "Giz",
    "Lamparina",
    "Lanterna coberta", "Lanterna",
    "Lanterna olho de boi",
    "Lenha",
    "Mochila",
    "Odre", "Cantil",
    "Óleo",
    "Pá",
    "Panela de ferro", "Panela",
    "Papel",
    "Pé de Cabra",
    "Pederneira e Aço",
    "Pedra de Amolar",
    "Pergaminho",
    "Polia e corda",
    "Rede de pesca",
    "Sabão",
    "Saco",
    "Saco de dormir",
    "Tela",
    "Tenda de lona", "Tenda",
    "Tocha",
    "Vara",
    "Vela",

    // Kits/Ferramentas
    "Bolsa de componentes mágicos",
    "Ferramentas de Artesão",
    "Ferramentas de Ladrão",
    "Grimório", "Grimório (em branco)",
    "Instrumento Musical",
    "Kit de Aventureiro",
    "Luneta",
    "Lupa",
    "Marreta",
    "Martelo",
    "Picareta de mineiro", "Picareta de mineração", "Picareta",
    "Régua de mercador",
    "Símbolo Sagrado", "Símbolo Sagrado (madeira)", "Símbolo Sagrado (prata)",

    // Kits Especiais
    "Kit de Curandeiro",
    "Kit de Disfarce",
    "Kit de Escalada",

    // 3. Vestuário, Comida e Serviços
    "Traje de Artesão",
    "Traje de frio", "Roupas de frio",
    "Traje de Mercador",
    "Traje de Nobre", "Roupas finas",
    "Traje de Viajante", "Roupas comuns",
    "Traje Real",

    // Consumíveis
    "Ale", "Cerveja",
    "Banquete",
    "Frutas secas",
    "Pão", "Broa",
    "Queijo",
    "Ração animal",
    "Rações de Viagem", "Rações",
    "Refeição", "Refeição Pobre", "Refeição Comum", "Refeição Boa",
    "Vinho",

    // 4. Animais e Montarias
    "Burro", "Mula",
    "Cão de guarda",
    "Cavalo leve", "Cavalo",
    "Cavalo pesado", "Cavalo de Guerra",
    "Pônei leve", "Pônei",
    "Pônei pesado",

    // Acessórios
    "Alforjes",
    "Freio e Arreio", "Equipamento de cavalgar",
    "Sela de cavalgar", "Sela",
    "Sela de guerra",

    // 5. Armaduras e Escudos
    // Leve
    "Armadura de Couro Batido",
    "Corselete de Couro",
    "Túnica", "Gibão", "Túnica Acolchoada",
    "Perneiras de Couro",
    "Capuz de Couro",

    // Média
    "Cota de Malha", "Camisão de Cota",
    "Cota de Escamas",
    "Camisão de Malha",
    "Perneiras de Malha",
    "Capuz de Cota", "Elmo de Malha",

    // Pesada
    "Malha de Placas",
    "Peitoral de Aço", "Placa de Peito",
    "Braçadeiras de Placas", "Braçadeiras",
    "Grevas de Placas", "Grevas",
    "Elmo Pesado",
    "Elmo Pesado Fechado",

    // Barda
    "Barda de Couro",
    "Barda de Malha",
    "Barda de Placas",

    // Escudos
    "Escudo Leve", "Escudo Pequeno",
    "Escudo Médio",
    "Escudo Pesado", "Escudo Grande",
    "Escudo com Espinhos",

    // Extras
    "Armadura de Espinhos",
    "Manopla fechada",

    // 6. Armas
    // Corpo a Corpo
    "Adaga", "Faca",
    "Alabarda",
    "Alfange",
    "Cajado", "Bastão",
    "Chicote",
    "Cimitarra",
    "Clava Leve",
    "Clava Pesada",
    "Corrente com Cravos", "Corrente com Espinhos",
    "Espada Bastarda",
    "Espada Curta",
    "Espada Grande",
    "Espada Longa",
    "Faca Estrela",
    "Foice",
    "Glaive",
    "Guisarme", "Bisarma",
    "Katana",
    "Lança",
    "Lança Curta",
    "Lança de Cavalaria",
    "Maça Leve",
    "Maça Pesada",
    "Maça-estrela",
    "Machado de Batalha", "Machado de Guerra",
    "Machado de Mão",
    "Machado Grande",
    "Malho",
    "Mangual",
    "Mangual Pesado",
    "Martelo de Guerra",
    "Pique",
    "Ranseur",
    "Rapieira",
    "Sai",
    "Segadeira", "Gadanha",
    "Tridente",
    "Espada do Templo",

    // Distância
    "Arco Composto",
    "Arco Curto",
    "Arco Longo",
    "Besta de Mão",
    "Besta de Mão de Repetição",
    "Besta Leve",
    "Besta Leve de Repetição",
    "Besta Pesada",
    "Besta Pesada de Repetição",
    "Boleadeira",
    "Funda",
    "Rede", "Rede (Balanceada)",
    "Shuriken",
    "Zarabatana",

    // Munição
    "Dardos",
    "Flechas", "Virotes", "Flechas/Virotes",
    "Pedras de funda",
    "Setas",

    // Cerco e Especiais
    "Aríete",
    "Balista",
    "Catapulta",
    "Torre de Cerco",
    "Trabuco",
    "Canhão", "Canhões",
    "Bala Sólida", "Balas Sólidas",

    // 7. Itens Alquímicos
    "Ácido", "Frasco de Ácido",
    "Água Benta",
    "Antitoxina",
    "Bastão de Fumaça",
    "Bastão Solar",
    "Bolsa Enredapé",
    "Fogo Alquímico",
    "Fósforos",
    "Pedra Trovão", "Pedra-Trovão",
    "Tocha da Chama Eterna", "Tocha Eterna",
    "Bússola de Guia",

    // 8. Veículos
    "Carroça",
    "Carroção leve",
    "Carroção pesado",
    "Carruagem",
    "Trenó",
    "Aeronave",
    "Dragão Alquímico",
    "Planador",
    "Barcaça",
    "Barco a Remo",
    "Corveta",
    "Galé",
    "Navio",
    "Navio de Guerra", "Galeão",
    "Veleiro"
)
