package com.example.swadebuilder.model

val SAVAGE_PATHFINDER_ALLOWLIST = setOf(
    // 1. Materiais Especiais
    "Adamante",
    "Madeira Negra",
    "Couro de Dragão",
    "Ferro Frio",
    "Mithral",
    "Prata Alquímica",

    // 2. Equipamento de Aventura e Ferramentas - Geral
    "Agulha", "Agulha de Costura",
    "Algemas",
    "Ampulheta",
    "Anzol",
    "Apito de cerâmica", "Apito",
    "Arpéu",
    "Bolsa de cinto", "Bolsa",
    "Caneca", "Caneca de cerâmica", "Copo de cerâmica", "Caneca (cerâmica)",
    "Caneta Tinteiro",
    "Cera de Vedação", "Cera para lacre", "Cera para lacre (barra)",
    "Cesto", "Cesta",
    "Cobertor",
    "Corda de cânhamo", "Corda", "Corda, cânhamo (10 quadros/20 metros)", "Corda de cânhamo (10 quadros/20m)",
    "Corda de seda",
    "Corrente", "Corrente (5 quadros/10m)",
    "Espelho pequeno de aço", "Espelho pequeno", "Espelho pequeno (aço)",
    "Espigão", "Pitão", "Espinhos/pitão (10)",
    "Estojo de mapa", "Estojo de pergaminho", "Estojo de mapa ou pergaminho",
    "Estrepes",
    "Frasco de cerâmica", "Jarro de cerâmica", "Frasco (cerâmica)", "Frasco (metal)",
    "Frasco pequeno", "Frasco",
    "Garrafa de vidro", "Garrafa",
    "Giz", "Giz (caixa com 12)",
    "Lamparina", "Lamparina (4 horas, 4 quadros de raio)",
    "Lanterna coberta", "Lanterna", "Lanterna (feixe de 10 quadros)",
    "Lanterna olho de boi",
    "Lenha",
    "Mochila", "Mochila (vazia)",
    "Odre", "Cantil", "Cantil (odre)", "Odre (vazio)",
    "Óleo", "Óleo (para lamparina: meio litro)", "Óleo (meio litro)",
    "Pá", "Pá pequena",
    "Panela de ferro", "Panela", "Panela (ferro)",
    "Papel",
    "Pé de Cabra",
    "Pederneira e Aço",
    "Pedra de Amolar", "Pedra de amolar",
    "Pergaminho", "Pergaminho (por folha)",
    "Polia e corda",
    "Rede de pesca",
    "Sabão",
    "Saco", "Saco grande", "Saco pequeno",
    "Saco de dormir", "Saco de dormir (preparado para o inverno)",
    "Tela", "Tela (m²)",
    "Tenda de lona", "Tenda", "Tenda (6 pessoas)", "Tenda de acampamento (2 pessoas)", "Tenda de pavilhão (15 pessoas)",
    "Tocha", "Tocha (uma hora, 4 quadros de raio)",
    "Vara", "Haste (3,5 metros)",
    "Vela", "Vela (uma hora, 2 quadros de raio)",
    "Baú (grande)", "Baú (pequeno)", "Caixote", "Barril", "Diário em branco", "Pena", "Sino", "Tinta (frasco)",

    // Kits/Ferramentas
    "Bolsa de componentes mágicos",
    "Ferramentas de Artesão",
    "Ferramentas de Ladrão", "Ferramentas de ladrão",
    "Grimório", "Grimório (em branco)", "Grimório em branco",
    "Instrumento Musical", "Instrumento musical",
    "Kit de Aventureiro",
    "Luneta",
    "Lupa",
    "Marreta",
    "Martelo",
    "Picareta de mineiro", "Picareta de mineração", "Picareta",
    "Régua de mercador",
    "Símbolo Sagrado", "Símbolo Sagrado (madeira)", "Símbolo Sagrado (prata)", "Símbolo sagrado (ouro)",

    // Kits Especiais
    "Kit de Curandeiro",
    "Kit de Disfarce",
    "Kit de Escalada",
    "Kit de armadilhas", "Kit de Artífice", "Kit de costura",
    // Kits de Classe
    "Kit de alquimista", "Kit de artista", "Kit de clérigo", "Kit de explorador", "Kit de explorador de masmorras",
    "Kit de ladrão", "Kit de mago", "Kit de mercenário",

    // 3. Vestuário, Comida e Serviços
    "Traje de Artesão",
    "Traje de frio", "Roupas de frio",
    "Traje de Mercador",
    "Traje de Nobre", "Roupas finas",
    "Traje de Viajante", "Roupas comuns",
    "Traje Real", "Roupas formais",
    "Botas pesadas", "Manto leve com capuz", "Botas de Inverno", "Botas, Caminhada", "Equipamento de Inverno (capa/jaqueta)",

    // Consumíveis
    "Ale", "Cerveja", "Cerveja (3,5 litros)", "Cerveja caneca",
    "Banquete", "Banquete (por pessoa)",
    "Frutas secas",
    "Pão", "Broa",
    "Queijo",
    "Ração animal", "Alimentação de animal (1 dia)",
    "Rações de Viagem", "Rações", "Rações (1 dia)", "Rações de luxo (1 dia)",
    "Refeição", "Refeição Pobre", "Refeição Comum", "Refeição Boa", "Refeição barata", "Refeição fina", "Refeição média", "1 litro de água (1 dia)",
    "Vinho", "Vinho (taça)", "Vinho (garrafa)",

    // 4. Animais e Montarias
    "Burro", "Mula", "Mula/burro",
    "Cão de guarda",
    "Cavalo leve", "Cavalo", "Cavalo de montaria",
    "Cavalo pesado", "Cavalo de Guerra", "Cavalo de guerra",
    "Pônei leve", "Pônei",
    "Pônei pesado",
    "Camelo", "Elefante", "Gavião/falcão",

    // Acessórios
    "Alforjes",
    "Freio e Arreio", "Equipamento de cavalgar",
    "Sela de cavalgar", "Sela",
    "Sela de guerra", "Sela Elaborada",

    // 5. Armaduras e Escudos
    // Leve
    "Armadura de Couro Batido",
    "Corselete de Couro",
    "Túnica", "Gibão", "Túnica Acolchoada", "Túnica (tronco, braços)",
    "Perneiras de Couro", "Perneiras",
    "Capuz de Couro", "Capuz de Couro (cabeça)",
    "Jaqueta Couro (tronco, braços)", "Manto Couro (tronco, braços, pernas)", "Calças Couro (pernas)",
    "Jaqueta Grossa (tronco, braços)", "Calças Grossas (pernas)", "Capuz Grosso (cabeça)",
    "Túnica ou Jaqueta de Couro (tronco, braços)", "Camisão de Couro (tronco, braços)",
    "Manto com capuz (tronco, cabeça)", "Robe com capuz (tronco, braços, cabeça)",

    // Média
    "Cota de Malha", "Camisão de Cota", "Camisão de Cota (tronco, braços)", "Calças de Cota (pernas)", "Capuz de Cota ou Elmo (cabeça)",
    "Cota de Escamas",
    "Camisão de Malha", "Camisa Malha (tronco, braços)", "Calças Malha (pernas)", "Capuz de Cota ou Elmo Malha (cabeça)",
    "Perneiras de Malha",
    "Capuz de Cota", "Elmo de Malha",
    "Corselete de Bronze (tronco)", "Grevas de Bronze (pernas)", "Braçadeiras de Bronze (braços)", "Elmo de Bronze (cabeça)",

    // Pesada
    "Malha de Placas",
    "Peitoral de Aço", "Placa de Peito", "Placa de Peito (tronco)",
    "Braçadeiras de Placas", "Braçadeiras", "Braçadeiras de Placas (braços)", "Braçadeiras ou Manoplas (braços)",
    "Grevas de Placas", "Grevas", "Grevas de Placas (pernas)", "Grevas (pernas)",
    "Elmo Pesado", "Elmo Pesado (cabeça)", "Elmo Pesado de Placas (cabeça)",
    "Elmo Pesado Fechado", "Elmo Pesado Fechado (cabeça)", "Elmo Pesado de Placas, Fechado (cabeça)",
    "Corselete de Placas (tronco)",

    // Barda
    "Barda de Couro", "Couro",
    "Barda de Malha",
    "Barda de Placas", "Placas",
    "Tecido Acolchoado", "Bronze",

    // Escudos
    "Escudo Leve", "Escudo Pequeno", "Pequeno (broquéis, targes)", "Medieval Pequeno",
    "Escudo Médio", "Médio", "Medieval Médio",
    "Escudo Pesado", "Escudo Grande", "Grande (torre, pavês)", "Medieval Grande",
    "Escudo com Espinhos",

    // Extras
    "Armadura de Espinhos",
    "Manopla fechada",

    // 6. Armas
    // Corpo a Corpo
    "Adaga", "Faca", "Adaga/Faca",
    "Alabarda",
    "Alfange",
    "Cajado", "Bastão", "Bastão/Cajado",
    "Chicote",
    "Cimitarra",
    "Clava Leve",
    "Clava Pesada",
    "Corrente com Cravos", "Corrente com Espinhos",
    "Espada Bastarda",
    "Espada Curta",
    "Espada Grande",
    "Espada Longa",
    "Faca Estrela",
    "Foice",
    "Glaive",
    "Guisarme", "Bisarma",
    "Katana",
    "Lança",
    "Lança Curta",
    "Lança de Cavalaria",
    "Maça Leve", "Maça",
    "Maça Pesada",
    "Maça-estrela", "Maça Estrela",
    "Machado de Batalha", "Machado de Guerra",
    "Machado de Mão",
    "Machado Grande",
    "Malho",
    "Mangual",
    "Mangual Pesado",
    "Martelo de Guerra",
    "Pique",
    "Ranseur",
    "Rapieira",
    "Sai",
    "Segadeira", "Gadanha",
    "Tridente",
    "Espada do Templo",
    "Espada Gancho", "Chakram", "Derrubador", "Manopla com Espinhos", "Martelo Meteoro", "Podão de Guerra", "Porrete", "Sabre de Abordagem",

    // Distância
    "Arco Composto",
    "Arco Curto", "Arco",
    "Arco Longo",
    "Besta de Mão",
    "Besta de Mão de Repetição",
    "Besta Leve", "Besta",
    "Besta Leve de Repetição",
    "Besta Pesada", "Besta, Pesada",
    "Besta Pesada de Repetição",
    "Boleadeira",
    "Funda",
    "Rede", "Rede (Balanceada)", "Rede (com pesos)",
    "Shuriken",
    "Zarabatana",
    "Lança/Dardo", "Lança/Azaguaia", "Machado, Arremesso",

    // Munição
    "Dardos",
    "Flechas", "Virotes", "Flechas/Virotes", "Aljava (guarda até 20 flechas/virotes)",
    "Pedras de funda",
    "Setas",

    // Cerco e Especiais
    "Aríete",
    "Balista",
    "Catapulta",
    "Torre de Cerco",
    "Trabuco",
    "Canhão", "Canhões", "Canhão (12 lb)", "Canhão (6 kg)",
    "Bala Sólida", "Balas Sólidas", "Estilhaço", "Metralha",

    // 7. Itens Alquímicos
    "Ácido", "Frasco de Ácido",
    "Água Benta",
    "Antitoxina",
    "Bastão de Fumaça",
    "Bastão Solar",
    "Bolsa Enredapé",
    "Fogo Alquímico",
    "Fósforos",
    "Pedra Trovão", "Pedra-Trovão",
    "Tocha da Chama Eterna", "Tocha Eterna",
    "Bússola de Guia", "Bolsa de Alquimista",

    // 8. Veículos
    "Carroça",
    "Carroção leve",
    "Carroção pesado",
    "Carruagem",
    "Trenó",
    "Aeronave",
    "Dragão Alquímico",
    "Planador",
    "Barcaça",
    "Barco a Remo",
    "Corveta",
    "Galé",
    "Navio",
    "Navio de Guerra", "Galeão",
    "Veleiro",
    "Carrinho (150 kg cap.)", "Carrinho de mão"
)

val SAVAGE_PATHFINDER_BLOCKED_SKILLS = setOf(
    "PSIONICOS",
    "ELETRONICA",
    "HACKEAR",
    "CIENCIA",
    "PILOTAR"
)
