name: Build Debug APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the APK'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708

      - name: Build APK (FullDebug)
        run: ./gradlew :app:assembleFullDebug --stacktrace

      - name: Sanitize artifact name
        run: echo "ARTIFACT_NAME=$(echo '${{ github.event.inputs.branch }}' | tr '/' '-')" >> $GITHUB_ENV

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks-${{ env.ARTIFACT_NAME }}
          path: app/build/outputs/apk/**/*.apk
