name: Build Debug APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build the APK'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.imputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK (FullDebug)
        run: ./gradlew :app:assembleFullDebug --stacktrace

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks-${{ github.event.inputs.branch }}
          path: app/build/outputs/apk/**/*.apk
